Revert "Revert "okhttp: Get tcmiface off the boot classpath""
This commit will cause bootloop at my device ZUK Z2 plus and ZUK Z2 pro because of this

E Zygote  : Error preloading com.android.okhttp.ConnectionPool.
E Zygote  : java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

F dex2oat : art/compiler/elf_writer.cc:62] Check failed: elf_file.get() != nullptr Failed to find expected EI_CLASS value 1 or 2 in /data/dalvik-cache/arm64/system@framework@boot.oat, found 0
F dex2oat : art/runtime/runtime.cc:422] Runtime aborting...

This reverts commit 7280a3f77be749b04fa28a9a7d65a10f3c78993b.